// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK7QVR3RLtZkZV2AW3pe1P0UK6OopoKyY',
    appId: '1:1029484641583:web:1c9377d2ffae9eec7bb5da',
    messagingSenderId: '1029484641583',
    projectId: 'enma-f8fbf',
    authDomain: 'enma-f8fbf.firebaseapp.com',
    storageBucket: 'enma-f8fbf.firebasestorage.app',
    measurementId: 'G-FZQR1NJCY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWyJe_NW7K4PVyhyP-Rc3AmJ1_yb9bpJs',
    appId: '1:1029484641583:android:18ff79eb619001177bb5da',
    messagingSenderId: '1029484641583',
    projectId: 'enma-f8fbf',
    storageBucket: 'enma-f8fbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSn13CMyopCM_TbN5lYjpauR7iePw7FYk',
    appId: '1:1029484641583:ios:13ef8af39eebbd207bb5da',
    messagingSenderId: '1029484641583',
    projectId: 'enma-f8fbf',
    storageBucket: 'enma-f8fbf.appspot.com',
    iosBundleId: 'com.example.enmaUdec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSn13CMyopCM_TbN5lYjpauR7iePw7FYk',
    appId: '1:1029484641583:ios:13ef8af39eebbd207bb5da',
    messagingSenderId: '1029484641583',
    projectId: 'enma-f8fbf',
    storageBucket: 'enma-f8fbf.appspot.com',
    iosBundleId: 'com.example.enmaUdec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK7QVR3RLtZkZV2AW3pe1P0UK6OopoKyY',
    appId: '1:1029484641583:web:25155647c9cd34b97bb5da',
    messagingSenderId: '1029484641583',
    projectId: 'enma-f8fbf',
    authDomain: 'enma-f8fbf.firebaseapp.com',
    storageBucket: 'enma-f8fbf.firebasestorage.app',
    measurementId: 'G-MQ6QH0B86L',
  );
}
